# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

version: "2"
run:
  timeout: 5m
  modules-download-mode: readonly
  issues-exit-code: 1

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gosec
    - prealloc
    - unconvert
    - misspell
    - revive
    - bodyclose
    - noctx
    - sqlclosecheck
    - wastedassign
    - exportloopref
    - goconst
    - gocritic
    - godot
    - lll
  disable:
    - depguard

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/aureum
  lll:
    line-length: 120
  godot:
    scope: declarations
  gosec:
    excludes:
      - G107
      - G404
  revive:
    rules:
      - name: exported
        severity: warning
      - name: blank-imports
      - name: context-as-argument
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - lll
        - gosec
        - errcheck
    - path: cmd/
      linters:
        - lll
    - path: migrations/
      linters:
        - lll
