version: "2"

run:
  timeout: 5m

linters-settings:
  errcheck:
    exclude-functions:
      - (*os.File).Close
      - (io.ReadCloser).Close
      - (net.Conn).Close
      - (net/http.Response).Body.Close
      - github.com/redis/go-redis/v9.(*Client).Close

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - noctx
        - bodyclose
        - lll
        - unused
