apiVersion: v1
kind: Service
metadata:
  name: report-svc
  namespace: default
  labels:
    app: report-svc
spec:
  selector:
    app: report-svc
  ports:
    - name: grpc
      port: 50059
      targetPort: 50059
      protocol: TCP
    - name: metrics
      port: 9099
      targetPort: 9099
      protocol: TCP
  type: ClusterIP
