apiVersion: v1
kind: Service
metadata:
  name: transaction-svc
  namespace: default
  labels:
    app: transaction-svc
spec:
  selector:
    app: transaction-svc
  ports:
    - name: grpc
      port: 50054
      targetPort: 50054
      protocol: TCP
    - name: metrics
      port: 9094
      targetPort: 9094
      protocol: TCP
  type: ClusterIP
