// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Transaction interface {
	IsTransaction()
}

type FixedExpense struct {
	ID            string            `json:"id"`
	UserID        string            `json:"userId"`
	Description   string            `json:"description"`
	Category      string            `json:"category"`
	DayOfMonth    int               `json:"dayOfMonth"`
	PaymentMethod PaymentMethod     `json:"paymentMethod"`
	Status        TransactionStatus `json:"status"`
	CreatedAt     time.Time         `json:"createdAt"`
	UpdatedAt     time.Time         `json:"updatedAt"`
}

func (FixedExpense) IsTransaction() {}

type FixedExpenseConnection struct {
	Edges      []*FixedExpenseEdge `json:"edges"`
	PageInfo   *PageInfo           `json:"pageInfo"`
	TotalCount int                 `json:"totalCount"`
}

type FixedExpenseEdge struct {
	Node   *FixedExpense `json:"node"`
	Cursor string        `json:"cursor"`
}

type Income struct {
	ID             string            `json:"id"`
	UserID         string            `json:"userId"`
	Description    string            `json:"description"`
	Source         string            `json:"source"`
	IncomeType     IncomeType        `json:"incomeType"`
	ReceivedDate   time.Time         `json:"receivedDate"`
	ReceivedAmount int64             `json:"receivedAmount"`
	Status         TransactionStatus `json:"status"`
	CreatedAt      time.Time         `json:"createdAt"`
	UpdatedAt      time.Time         `json:"updatedAt"`
}

func (Income) IsTransaction() {}

type IncomeConnection struct {
	Edges      []*IncomeEdge `json:"edges"`
	PageInfo   *PageInfo     `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}

type IncomeEdge struct {
	Node   *Income `json:"node"`
	Cursor string  `json:"cursor"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type TransactionConnection struct {
	Edges      []*TransactionEdge `json:"edges"`
	PageInfo   *PageInfo          `json:"pageInfo"`
	TotalCount int                `json:"totalCount"`
}

type TransactionEdge struct {
	Node   Transaction `json:"node"`
	Cursor string      `json:"cursor"`
}

type UserProfile struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type VariableExpense struct {
	ID            string            `json:"id"`
	UserID        string            `json:"userId"`
	Description   string            `json:"description"`
	Destination   string            `json:"destination"`
	Category      string            `json:"category"`
	ExpenseType   ExpenseType       `json:"expenseType"`
	PaymentMethod PaymentMethod     `json:"paymentMethod"`
	PaymentDate   time.Time         `json:"paymentDate"`
	PaidAmount    int64             `json:"paidAmount"`
	Status        TransactionStatus `json:"status"`
	CreatedAt     time.Time         `json:"createdAt"`
	UpdatedAt     time.Time         `json:"updatedAt"`
}

func (VariableExpense) IsTransaction() {}

type VariableExpenseConnection struct {
	Edges      []*VariableExpenseEdge `json:"edges"`
	PageInfo   *PageInfo              `json:"pageInfo"`
	TotalCount int                    `json:"totalCount"`
}

type VariableExpenseEdge struct {
	Node   *VariableExpense `json:"node"`
	Cursor string           `json:"cursor"`
}

type ExpenseType string

const (
	ExpenseTypeEssential     ExpenseType = "ESSENTIAL"
	ExpenseTypeDiscretionary ExpenseType = "DISCRETIONARY"
	ExpenseTypeOccasional    ExpenseType = "OCCASIONAL"
	ExpenseTypeEmergency     ExpenseType = "EMERGENCY"
	ExpenseTypeOther         ExpenseType = "OTHER"
)

var AllExpenseType = []ExpenseType{
	ExpenseTypeEssential,
	ExpenseTypeDiscretionary,
	ExpenseTypeOccasional,
	ExpenseTypeEmergency,
	ExpenseTypeOther,
}

func (e ExpenseType) IsValid() bool {
	switch e {
	case ExpenseTypeEssential, ExpenseTypeDiscretionary, ExpenseTypeOccasional, ExpenseTypeEmergency, ExpenseTypeOther:
		return true
	}
	return false
}

func (e ExpenseType) String() string {
	return string(e)
}

func (e *ExpenseType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ExpenseType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ExpenseType", str)
	}
	return nil
}

func (e ExpenseType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ExpenseType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ExpenseType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type IncomeType string

const (
	IncomeTypeSalary     IncomeType = "SALARY"
	IncomeTypeFreelance  IncomeType = "FREELANCE"
	IncomeTypeInvestment IncomeType = "INVESTMENT"
	IncomeTypeBusiness   IncomeType = "BUSINESS"
	IncomeTypeRefund     IncomeType = "REFUND"
	IncomeTypeOther      IncomeType = "OTHER"
)

var AllIncomeType = []IncomeType{
	IncomeTypeSalary,
	IncomeTypeFreelance,
	IncomeTypeInvestment,
	IncomeTypeBusiness,
	IncomeTypeRefund,
	IncomeTypeOther,
}

func (e IncomeType) IsValid() bool {
	switch e {
	case IncomeTypeSalary, IncomeTypeFreelance, IncomeTypeInvestment, IncomeTypeBusiness, IncomeTypeRefund, IncomeTypeOther:
		return true
	}
	return false
}

func (e IncomeType) String() string {
	return string(e)
}

func (e *IncomeType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = IncomeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid IncomeType", str)
	}
	return nil
}

func (e IncomeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *IncomeType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e IncomeType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PaymentMethod string

const (
	PaymentMethodCreditCard   PaymentMethod = "CREDIT_CARD"
	PaymentMethodDebitCard    PaymentMethod = "DEBIT_CARD"
	PaymentMethodCash         PaymentMethod = "CASH"
	PaymentMethodBankTransfer PaymentMethod = "BANK_TRANSFER"
	PaymentMethodPix          PaymentMethod = "PIX"
	PaymentMethodOther        PaymentMethod = "OTHER"
)

var AllPaymentMethod = []PaymentMethod{
	PaymentMethodCreditCard,
	PaymentMethodDebitCard,
	PaymentMethodCash,
	PaymentMethodBankTransfer,
	PaymentMethodPix,
	PaymentMethodOther,
}

func (e PaymentMethod) IsValid() bool {
	switch e {
	case PaymentMethodCreditCard, PaymentMethodDebitCard, PaymentMethodCash, PaymentMethodBankTransfer, PaymentMethodPix, PaymentMethodOther:
		return true
	}
	return false
}

func (e PaymentMethod) String() string {
	return string(e)
}

func (e *PaymentMethod) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PaymentMethod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PaymentMethod", str)
	}
	return nil
}

func (e PaymentMethod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PaymentMethod) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PaymentMethod) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TransactionStatus string

const (
	TransactionStatusPending   TransactionStatus = "PENDING"
	TransactionStatusCompleted TransactionStatus = "COMPLETED"
	TransactionStatusCancelled TransactionStatus = "CANCELLED"
)

var AllTransactionStatus = []TransactionStatus{
	TransactionStatusPending,
	TransactionStatusCompleted,
	TransactionStatusCancelled,
}

func (e TransactionStatus) IsValid() bool {
	switch e {
	case TransactionStatusPending, TransactionStatusCompleted, TransactionStatusCancelled:
		return true
	}
	return false
}

func (e TransactionStatus) String() string {
	return string(e)
}

func (e *TransactionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TransactionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TransactionStatus", str)
	}
	return nil
}

func (e TransactionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TransactionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TransactionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TransactionTypeFilter string

const (
	TransactionTypeFilterIncome          TransactionTypeFilter = "INCOME"
	TransactionTypeFilterFixedExpense    TransactionTypeFilter = "FIXED_EXPENSE"
	TransactionTypeFilterVariableExpense TransactionTypeFilter = "VARIABLE_EXPENSE"
)

var AllTransactionTypeFilter = []TransactionTypeFilter{
	TransactionTypeFilterIncome,
	TransactionTypeFilterFixedExpense,
	TransactionTypeFilterVariableExpense,
}

func (e TransactionTypeFilter) IsValid() bool {
	switch e {
	case TransactionTypeFilterIncome, TransactionTypeFilterFixedExpense, TransactionTypeFilterVariableExpense:
		return true
	}
	return false
}

func (e TransactionTypeFilter) String() string {
	return string(e)
}

func (e *TransactionTypeFilter) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TransactionTypeFilter(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TransactionTypeFilter", str)
	}
	return nil
}

func (e TransactionTypeFilter) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TransactionTypeFilter) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TransactionTypeFilter) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
