apiVersion: v1
kind: Service
metadata:
  name: identity-svc
  namespace: default
  labels:
    app: identity-svc
spec:
  selector:
    app: identity-svc
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: grpc
      port: 9090
      targetPort: 9090
      protocol: TCP
  type: ClusterIP
