apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: budget-svc-config
    literals:
      - cache_ttl=5m
      - idempotency_ttl=24h
