apiVersion: v1
kind: Service
metadata:
  name: budget-svc
  namespace: default
  labels:
    app: budget-svc
spec:
  selector:
    app: budget-svc
  ports:
    - name: grpc
      port: 50055
      targetPort: 50055
      protocol: TCP
    - name: metrics
      port: 9096
      targetPort: 9096
      protocol: TCP
  type: ClusterIP
