apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: transaction-svc
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: graphql-bff
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2
            memory: 1Gi
    target:
      kind: Deployment
      name: transaction-svc
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2
            memory: 1Gi
    target:
      kind: Deployment
      name: graphql-bff
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: transaction-svc-hpa
      spec:
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: transaction-svc
        minReplicas: 3
        maxReplicas: 10
        metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 70
    target:
      kind: Deployment
      name: transaction-svc
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: graphql-bff-hpa
      spec:
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: graphql-bff
        minReplicas: 3
        maxReplicas: 10
        metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 70
    target:
      kind: Deployment
      name: graphql-bff
  - patch: |-
      apiVersion: policy/v1
      kind: PodDisruptionBudget
      metadata:
        name: transaction-svc-pdb
      spec:
        minAvailable: 2
        selector:
          matchLabels:
            app: transaction-svc
    target:
      kind: Deployment
      name: transaction-svc
  - patch: |-
      apiVersion: policy/v1
      kind: PodDisruptionBudget
      metadata:
        name: graphql-bff-pdb
      spec:
        minAvailable: 2
        selector:
          matchLabels:
            app: graphql-bff
    target:
      kind: Deployment
      name: graphql-bff
